player_stats <- hoopR::load_nba_player_stats(2025)
team_stats <- hoopR::load_nba_team_stats(2025)

cat("PLAYER_COLUMNS\n")
dput(names(player_stats))
cat("\nPLAYER_STAT_LABELS\n")
dput(sort(unique(player_stats$stat_label)))
cat("\nPLAYER_SAMPLE\n")
print(player_stats[player_stats$athlete_id == player_stats$athlete_id[[1]], c("category", "stat_label", "stat_name", "display_value", "value")], n = Inf)
cat("\nTEAM_COLUMNS\n")
dput(names(team_stats))
cat("\nTEAM_STAT_LABELS\n")
dput(sort(unique(team_stats$stat_label)))
cat("\nTEAM_SAMPLE\n")
print(utils::head(team_stats, 12))
